### ISSUE TITLE
Moving entities between projects - API dev - labkey-api-r

### ISSUE THREAD

**Issue by cnathe** [LabKey/labkey-api-r#99]
[Epic](https://github.com/LabKey/sampleManagement/issues/1652)
[Spec](https://docs.google.com/document/d/1yyD9UqQ0OZolrdQcI5El-Q2cRuG1TywmB8KJhBbAbKQ/edit#heading=h.qsar3b9omty4)

### Tasks 📍
- [x] add moveRows to package - 2h
- [x] add Rd man page - 1h
- [x] Code Review @labkey-klum 
- [x] Test review and merge 📍
